### ISSUE TITLE
Todo for Release 1.0

### ISSUE THREAD

**Issue by Art4** [youthweb/urllinker#1]
- [x] Testing and Code Coverage
- [x] Add a changelog
- [x] Update the IANA TLD list
- [x] Allow custom TLDs
- [x] Allow better configuration for features in future
- [x] create tests for the reported bugs at https://bitbucket.org/kwi/urllinker/issues?status=new&status=open
- [x] Add option not to convert emails to links

This fork of [kwi/urllinker](https://bitbucket.org/kwi/urllinker) is needed because:

- [kwi/urllinker](https://packagist.org/packages/kwi/urllinker) has no stable tag
- [there are some issues](https://bitbucket.org/kwi/urllinker/issues?status=new&status=open) that we had too, like customize the html links or don't parse emails
- the project seems to be abandoned since two years, also because @kwi-dk [don't use the project and has stopped using PHP](http://www.kwi.dk/about/portfolio/)
- there seems to be no stable and maintained fork

Nevertheless I have to say thank you to @kwi-dk and @MacDada for their great work of creating and maintaining this project so many years!

**Comment by Art4** [comment]
We just released UrlLinker 1.0 and will be soon available on Packagist.
https://github.com/youthweb/urllinker/releases
